[workspace]
resolver = "2"
members = [
    "crates/device-tree",
    "crates/elf",
    "crates/endian",
    "crates/init",
    "crates/kernel",
    "crates/lz4",
]

[profile.release]
opt-level = 2
strip = false
incremental = false
debug = 2
panic = "abort"

[profile.dev]
incremental = false
panic = "abort"
