[package]
name = "shell-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.21.0" }

ulib = { path = "../ulib", features = ["heap-impl"] }

[dev-dependencies]
ulib = { path = "../ulib", features = ["test"] }
