[package]
name = "networking"
version = "0.1.0"

[dependencies]
byteorder = "1.4"
log = "0.4"

[[app]]
name = "arping"

[[app]]
name = "dev_up"

[[app]]
name = "ping"

[[app]]
name = "traceroute"

[[app]]
name = "udp_cat"

[[app]]
name = "udp_echo"

